from .december01 import solve as december01
from .december02 import solve as december02
from .december03 import solve as december03
from .december04 import solve as december04
from .december05 import solve as december05
from .december06 import solve as december06
from .december07 import solve as december07
from .december08 import solve as december08
from .december09 import solve as december09
from .december10 import solve as december10
from .december11 import solve as december11
from .december12 import solve as december12
from .december13 import solve as december13
from .december14 import solve as december14
from .december15 import solve as december15
from .december16 import solve as december16
from .december17 import solve as december17
from .december18 import solve as december18
from .december19 import solve as december19
from .december20 import solve as december20
from .december21 import solve as december21
from .december22 import solve as december22
from .december23 import solve as december23
from .december24 import solve as december24
from .december25 import solve as december25
