from .december_01 import solve as december_01
from .december_02 import solve as december_02
from .december_03 import solve as december_03
from .december_04 import solve as december_04
from .december_05 import solve as december_05
from .december_06 import solve as december_06
from .december_07 import solve as december_07
from .december_08 import solve as december_08
from .december_09 import solve as december_09
from .december_10 import solve as december_10
from .december_11 import solve as december_11
from .december_12 import solve as december_12
from .december_13 import solve as december_13
from .december_14 import solve as december_14
from .december_15 import solve as december_15
from .december_16 import solve as december_16
from .december_17 import solve as december_17
from .december_18 import solve as december_18
from .december_19 import solve as december_19
from .december_20 import solve as december_20
from .december_21 import solve as december_21
from .december_22 import solve as december_22
from .december_23 import solve as december_23
from .december_24 import solve as december_24
from .december_25 import solve as december_25
